### PR TITLE
Fixed bug when making properties of top level members with anonymous types static

### LINKED ISSUE #48: Both a static and instance version of the same member can be generated when merging variables with interfaces
The dom.d.ts file has some declarations of the form:
```
declare interface ApplicationCache {
  readonly CHECKING: number;
  readonly DOWNLOADING: number;
  readonly IDLE: number;
  readonly OBSOLETE: number;
  readonly UNCACHED: number;
  readonly UPDATEREADY: number;
}

declare var ApplicationCache: {
  prototype: ApplicationCache;
  new (): ApplicationCache;
  readonly CHECKING: number;
  readonly DOWNLOADING: number;
  readonly IDLE: number;
  readonly OBSOLETE: number;
  readonly UNCACHED: number;
  readonly UPDATEREADY: number;
};
```

Which is generating Dart code with two copies of each member. The members from the variable declaration of ApplicationCache are static and the ones from the interface declaration are instance members. To avoid this we can combine members with the same name and keep the static modifier. After looking through the html_dart2js.dart and dom.widl files it appears as though the members in the variable declaration are indeed static constants.

### PR DESCRIPTION
**Pull request by derekxu16**
Now these properties become static on all classes in the hierarchy so that definitions match. This also fixed a bug where properties were being emitted twice when declared on both an interface and a variable of the same name

Fixes #48

### CODE REVIEW

File: lib/merge.ts [hunk 1]
```diff
@@ -374,9 +374,28 @@ export function normalizeSourceFile(f: ts.SourceFile, fc: FacadeConverter) {
...
+                      // Finds all existing declarations of this property in the inheritance
+                      // hierarchy of this class
+                      const existingDeclarations =
+                          findPropertyInHierarchy(base.ident(member.name), existing, classes);
+
+                      if (existingDeclarations.size) {
+                        // TODO(derekx): For dom.d.ts it makes sense to make all properties that are
+                        // declared on the anonymous types of top level variable declarations
+                        // static, but this may not always be correct
+                        for (const existingDecl of existingDeclarations) {
```
Comment (jacob314) [inline lib/merge.ts]: add a boolean to turn on and off this option.

File: lib/merge.ts [hunk 2]
```diff
@@ -374,9 +374,28 @@ export function normalizeSourceFile(f: ts.SourceFile, fc: FacadeConverter) {
...
+                          addModifier(existingDecl, ts.createModifier(ts.SyntaxKind.StaticKeyword));
+                        }
+                      }
+
+                      // If needed, add declaration of property to the interface that we are
+                      // currently handling
+                      if (!findPropertyInClass(base.ident(member.name), existing)) {
+                        addModifier(member, ts.createModifier(ts.SyntaxKind.StaticKeyword));
+                        member.parent = existing;
```
Comment (jacob314) [inline lib/merge.ts]: don't modify the TS ast as part of running the emitter. Instead keep whatever information you need in separate maps on the side.
Otherwise we could get really strange bugs.

File: lib/merge.ts [hunk 3]
```diff
@@ -402,6 +421,37 @@ export function normalizeSourceFile(f: ts.SourceFile, fc: FacadeConverter) {
...
+      undefined {
+    const members = classLike.members as ts.NodeArray<ts.ClassElement>;
+    return members.find((member: ts.ClassElement) => {
+      if (base.ident(member.name) === propName) {
+        return true;
+      }
+    });
+  }
+
+  function findPropertyInHierarchy(
```
Comment (jacob314) [inline lib/merge.ts]: sure there aren't existing ts methods that can perform these lookups?

**Comment by jacob314** [comment]
Discussed offline. Lgtm with a nit to add an extra CLI flag for the risky interpretation of fields.
lgtm

File: lib/merge.ts (hunk 3 above)
Comment (derekxu16) [reply lib/merge.ts]: I wasn't able to find anything
